import type { OrderTypeManifestEntry } from './types.js';

export const ORDER_TYPE_MANIFEST: OrderTypeManifestEntry[] = [
  {
    type: 'replenishment',
    displayName: '补货订单',
    access: 'financial-write',
    adapter: 'replenishment',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [{ funCode: 'b2b:order:create', name: '创建补货订单', requiredFor: 'submit' }],
  },
  {
    type: 'multi-store-replenishment',
    displayName: '多门店补货订单',
    access: 'ops-write',
    adapter: 'multi-store',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [
      { funCode: 'supply:multiStoreOrder:booking', name: '多门店订货', requiredFor: 'submit' },
      { funCode: 'b2b:order:multiSotreOrder:add', name: '新增多门店订单', requiredFor: 'submit' },
    ],
  },
  {
    type: 'mid-presale',
    displayName: '中短期订单',
    access: 'financial-write',
    adapter: 'mid-presale',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [{ funCode: 'mini:presale:order:save', name: '中短期下单', requiredFor: 'submit' }],
  },
  {
    type: 'supply-presale',
    displayName: '柔供预售订单',
    access: 'financial-write',
    adapter: 'supply-presale',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [
      { funCode: 'b2b:supply:presale:add', name: '柔供加购', requiredFor: 'submit' },
      { funCode: 'b2b:supply:presale:submit', name: '柔供提交', requiredFor: 'submit' },
    ],
  },
  {
    type: 'pickup',
    displayName: '预售提货单',
    access: 'financial-write',
    adapter: 'pickup',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [{ funCode: 'new:store:order:pickup', name: '提货下单', requiredFor: 'submit' }],
  },
  {
    type: 'new-store',
    displayName: '新店订单',
    access: 'financial-write',
    adapter: 'new-store',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [{ funCode: 'new:store:order:pickup', name: '新店提货', requiredFor: 'submit' }],
  },
  {
    type: 'pending-review',
    displayName: '待审核订单',
    access: 'financial-write',
    adapter: 'pending-review',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [{ funCode: 'pending:order:create', name: '创建待审核单', requiredFor: 'submit' }],
  },
  {
    type: 'one-piece-pending',
    displayName: '一件代发待审核补货',
    access: 'financial-write',
    adapter: 'pending-review',
    browser: false,
    canRead: true,
    canSubmit: true,
    requiredPermissions: [
      { funCode: 'mall:b2b:order:dropShipping', name: '一件代发', requiredFor: 'submit' },
      { funCode: 'pending:order:create', name: '创建待审核单', requiredFor: 'submit' },
    ],
  },
  {
    type: 'live-presale',
    displayName: '直播预售订单',
    access: 'financial-write',
    adapter: 'unsupported',
    browser: false,
    canRead: true,
    canSubmit: false,
    requiredPermissions: [{ funCode: 'mini:presale:order:save', name: '直播预售下单', requiredFor: 'submit' }],
  },
  {
    type: 'direct-package',
    displayName: '直铺包订单',
    access: 'ops-write',
    adapter: 'unsupported',
    browser: false,
    canRead: true,
    canSubmit: false,
    requiredPermissions: [{ funCode: 'mini:presale:order:save', name: '直铺包下单', requiredFor: 'submit' }],
  },
  {
    type: 'intellect-ai-replenishment',
    displayName: '智能 AI 补货',
    access: 'financial-write',
    adapter: 'replenishment',
    browser: false,
    canRead: true,
    canSubmit: false,
    requiredPermissions: [{ funCode: 'b2b:order:create', name: '创建补货订单', requiredFor: 'submit' }],
  },
  {
    type: 'sales-repurchase',
    displayName: '销售复购订单',
    access: 'financial-write',
    adapter: 'replenishment',
    browser: false,
    canRead: true,
    canSubmit: false,
    requiredPermissions: [{ funCode: 'b2b:order:create', name: '创建补货订单', requiredFor: 'submit' }],
  },
];

export function getOrderTypeManifest(type: string): OrderTypeManifestEntry | undefined {
  return ORDER_TYPE_MANIFEST.find((entry) => entry.type === type);
}
