export interface CommandManifestEntry {
  site: 'bmall';
  name: string;
  description: string;
  audience: 'customer' | 'ops' | 'core';
  access: 'read' | 'write' | 'destructive' | 'financial';
  domain: string;
  strategy: 'api-token' | 'api-login' | 'manual-token-import' | 'none';
  browser: boolean;
  loginBootstrap?: 'system-browser';
  args: Array<{ name: string; type: string; required?: boolean; help?: string }>;
  columns: string[];
}

type EntryInput = Omit<CommandManifestEntry, 'site' | 'domain' | 'browser' | 'args' | 'columns'> &
  Partial<Pick<CommandManifestEntry, 'domain' | 'browser' | 'args' | 'columns'>>;

const domain = 'bmall.semirapp.com';

function entry(input: EntryInput): CommandManifestEntry {
  return {
    site: 'bmall',
    domain,
    browser: false,
    args: [],
    columns: [],
    ...input,
  };
}

const orderColumns = ['orderType', 'status', 'blockingIssues', 'warnings', 'nextActions'];
const readToken = 'api-token' as const;

export const COMMAND_MANIFEST: CommandManifestEntry[] = [
  entry({ name: 'version', description: 'Print CLI version', audience: 'core', access: 'read', strategy: 'none', columns: ['version', 'node'] }),
  entry({ name: 'doctor', description: 'Check local CLI profile and environment', audience: 'core', access: 'read', strategy: 'none', columns: ['profile', 'env', 'baseUrl'] }),
  entry({ name: 'profile.list', description: 'List CLI profiles', audience: 'core', access: 'read', strategy: 'none', columns: ['activeProfile', 'profiles'] }),
  entry({ name: 'profile.use', description: 'Switch active CLI profile', audience: 'core', access: 'write', strategy: 'none', args: [{ name: 'name', type: 'str', required: true }], columns: ['profile', 'env'] }),
  entry({ name: 'profile.set-env', description: 'Configure a base URL for an environment', audience: 'core', access: 'write', strategy: 'none', args: [{ name: 'env', type: 'str', required: true }, { name: 'base-url', type: 'url', required: true }], columns: ['env', 'baseUrl'] }),
  entry({ name: 'manifest.list', description: 'List command manifest entries', audience: 'core', access: 'read', strategy: 'none', columns: ['name', 'audience', 'access', 'browser'] }),
  entry({ name: 'manifest.get', description: 'Get one command manifest entry', audience: 'core', access: 'read', strategy: 'none', args: [{ name: 'name', type: 'str', required: true }], columns: ['name', 'args', 'columns'] }),
  entry({ name: 'auth.import-token', description: 'Import a token or token bundle into a CLI profile', audience: 'core', access: 'read', strategy: 'manual-token-import', args: [{ name: 'token', type: 'str' }, { name: 'bundle', type: 'json' }, { name: 'from-file', type: 'path' }, { name: 'skip-verify', type: 'bool' }], columns: ['profile', 'env', 'userId', 'groupId'] }),
  entry({ name: 'auth.login', description: 'Login with browser-assisted loopback or account/password form', audience: 'core', access: 'read', strategy: 'api-login', loginBootstrap: 'system-browser', args: [{ name: 'browser', type: 'bool' }, { name: 'no-open', type: 'bool' }, { name: 'account', type: 'str' }, { name: 'password', type: 'str' }, { name: 'skip-verify', type: 'bool' }], columns: ['profile', 'env', 'callbackUrl'] }),
  entry({ name: 'auth.doctor', description: 'Check saved token and server identity', audience: 'core', access: 'read', strategy: readToken, columns: ['hasToken', 'serverUser'] }),
  entry({ name: 'auth.renew', description: 'Renew the saved token through manage/app/token/renewal', audience: 'core', access: 'write', strategy: readToken, columns: ['profile', 'env', 'bundle'] }),
  entry({ name: 'auth.logout', description: 'Delete saved credentials for a profile', audience: 'core', access: 'write', strategy: readToken, columns: ['loggedOut', 'profile'] }),
  entry({ name: 'agent.knowledge', description: 'Show bundled diagnostic knowledge pack metadata for external users', audience: 'core', access: 'read', strategy: 'none', columns: ['id', 'version', 'entries', 'sourceReposRequired', 'sourceKnowledge'] }),
  entry({ name: 'agent.explain-error', description: 'Explain known Bmall error codes using bundled diagnostic knowledge and remediation playbooks', audience: 'core', access: 'read', strategy: 'none', args: [{ name: 'error-code', type: 'str' }, { name: 'message', type: 'str' }], columns: ['code', 'knowledgePack', 'evidence', 'playbook', 'commands', 'supportBundleHints'] }),
  entry({ name: 'whoami', description: 'Show current Bmall identity', audience: 'core', access: 'read', strategy: readToken, columns: ['bundle', 'serverUser'] }),
  entry({ name: 'company.list', description: 'List companies available to the current token and active brand', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'sword', type: 'str', required: false }], columns: ['accountType', 'companyId', 'companyName', 'companyCode', 'groupId', 'scId'] }),
  entry({ name: 'company.use', description: 'Set active company context in the profile', audience: 'customer', access: 'write', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }, { name: 'company-name', type: 'str' }], columns: ['profile', 'companyId'] }),
  entry({ name: 'company.groups', description: 'List brand groups available to the current BMALL or IAM account', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'sword', type: 'str', required: false }], columns: ['accountType', 'sgId', 'groupId', 'groupName', 'groupCode'] }),
  entry({ name: 'company.switch-group', description: 'Switch active brand group and save the returned token bundle; BMALL supports sgId or groupId, IAM uses groupId', audience: 'customer', access: 'write', strategy: readToken, args: [{ name: 'sg-id', type: 'str', required: false }, { name: 'group-id', type: 'str', required: false }], columns: ['accountType', 'switched', 'group', 'bundle'] }),
  entry({ name: 'company.switch', description: 'Switch active login company/store and save the returned token bundle; BMALL supports scId or companyId, IAM uses companyId', audience: 'customer', access: 'write', strategy: readToken, args: [{ name: 'sc-id', type: 'str', required: false }, { name: 'company-id', type: 'str', required: false }], columns: ['accountType', 'switched', 'company', 'bundle'] }),
  entry({ name: 'permission.list', description: 'List current token permission codes', audience: 'ops', access: 'read', strategy: readToken, columns: ['funCode'] }),
  entry({ name: 'permission.check', description: 'Check a permission code against token bundle permissions and menu data', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'fun-code', type: 'str', required: true }], columns: ['funCode', 'allowed'] }),

  entry({ name: 'product.search', description: 'Search products by keyword or item filters', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'keyword', type: 'str' }, { name: 'limit', type: 'number' }, { name: 'company-id', type: 'str' }], columns: ['itemCode', 'itemName', 'skcCode'] }),
  entry({ name: 'product.get', description: 'Read product detail', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }, { name: 'item-id', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['itemCode', 'itemName'] }),
  entry({ name: 'product.sku', description: 'Read product SKU/spec matrix', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'skc-code', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['skuCode', 'specId', 'size', 'color'] }),
  entry({ name: 'product.size-ratio', description: 'Calculate size-ratio quantity suggestions', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'skc-code', type: 'str', required: true }, { name: 'quantity', type: 'number', required: true }, { name: 'company-id', type: 'str' }], columns: ['skuCode', 'quantity'] }),
  entry({ name: 'product.labels', description: 'Read product activity labels', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['labelCode', 'labelName'] }),
  entry({ name: 'stock.check', description: 'Check stock availability for SKU or item', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'sku-code', type: 'str', required: true }, { name: 'company-id', type: 'str', required: true }], columns: ['skuCode', 'availableQty'] }),
  entry({ name: 'cart.list', description: 'Read shopping cart', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'company-id', type: 'str' }], columns: ['skuCode', 'quantity'] }),
  entry({ name: 'cart.add', description: 'Add SKU to cart with write gate', audience: 'customer', access: 'write', strategy: readToken, args: [{ name: 'sku-code', type: 'str', required: true }, { name: 'qty', type: 'number', required: true }, { name: 'company-id', type: 'str' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['endpoint', 'body'] }),
  entry({ name: 'cart.remove', description: 'Remove SKU from cart with destructive gate', audience: 'customer', access: 'destructive', strategy: readToken, args: [{ name: 'sku-code', type: 'str', required: true }, { name: 'company-id', type: 'str' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['endpoint', 'body'] }),
  entry({ name: 'cart.clear', description: 'Clear cart with destructive gate', audience: 'customer', access: 'destructive', strategy: readToken, args: [{ name: 'company-id', type: 'str' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['endpoint', 'body'] }),

  entry({ name: 'order-type.list', description: 'List supported Bmall order types', audience: 'customer', access: 'read', strategy: readToken, columns: ['type', 'displayName', 'canSubmit', 'browser'] }),
  entry({ name: 'order-type.get', description: 'Get one supported Bmall order type by enum value', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str', required: true }], columns: ['type', 'displayName', 'canSubmit', 'browser'] }),
  entry({ name: 'order-flow.inspect', description: 'Inspect adapter endpoints and rule skeleton for an order type', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str', required: true }], columns: orderColumns }),
  entry({ name: 'order-rule.explain', description: 'Explain order rule-chain phases', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str', required: true }], columns: ['phase', 'status', 'summary'] }),
  entry({ name: 'order.plan', description: 'Build a deterministic order plan from a JSON draft', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: orderColumns }),
  entry({ name: 'order.validate', description: 'Validate an order draft without submitting', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }, { name: 'type', type: 'str' }], columns: orderColumns }),
  entry({ name: 'order.submit', description: 'Submit an order draft only when an API runtime is wired; offline confirmed submits are blocked', audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }, { name: 'type', type: 'str' }, { name: 'confirm', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['submitted', 'orderNo', 'status', 'message'] }),
  entry({ name: 'order.list', description: 'List orders', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'status', type: 'str' }, { name: 'from', type: 'str' }, { name: 'to', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['orderNo', 'status'] }),
  entry({ name: 'order.get', description: 'Read one order', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str', required: true }, { name: 'company-id', type: 'str' }], columns: ['orderNo', 'status'] }),
  entry({ name: 'order.cancel', description: 'Cancel an order with destructive gate', audience: 'customer', access: 'destructive', strategy: readToken, args: [{ name: 'order-no', type: 'str', required: true }, { name: 'company-id', type: 'str' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'order.delivery', description: 'Read order delivery information', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str', required: true }, { name: 'company-id', type: 'str' }], columns: ['invoiceNo', 'deliveryStatus'] }),
  entry({ name: 'order.invoice', description: 'Read order invoice information', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str', required: true }, { name: 'company-id', type: 'str' }], columns: ['invoiceNo', 'invoiceStatus'] }),

  ...['replenishment', 'multi-store-order'].flatMap((name) => [
    entry({ name: `${name}.plan`, description: `Build ${name} order plan`, audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: orderColumns }),
    entry({ name: `${name}.validate`, description: `Validate ${name} order`, audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: orderColumns }),
    entry({ name: `${name}.submit`, description: `Submit ${name} order only when an API runtime is wired`, audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }, { name: 'confirm', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['submitted', 'orderNo', 'status'] }),
    entry({ name: `${name}.diagnose`, description: `Diagnose ${name} order`, audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str' }, { name: 'order-id', type: 'str' }], columns: orderColumns }),
  ]),

  entry({ name: 'pending-order.plan', description: 'Build a deterministic pending-review draft plan without executing approval', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: orderColumns }),
  entry({ name: 'pending-order.validate', description: 'Validate pending-order flow', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: orderColumns }),
  entry({ name: 'pending-order.submit', description: 'Submit pending-order flow only when an API runtime is wired', audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }, { name: 'confirm', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['submitted', 'status', 'message'] }),
  entry({ name: 'pending-order.diagnose', description: 'Diagnose pending-order flow', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str' }, { name: 'order-id', type: 'str' }], columns: orderColumns }),
  entry({ name: 'mid-order.validate', description: 'Validate mid-order flow', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: orderColumns }),
  entry({ name: 'mid-order.submit', description: 'Submit mid-order flow only when an API runtime is wired', audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }, { name: 'resume-waiting-order', type: 'bool' }], columns: ['submitted', 'status', 'message'] }),
  entry({ name: 'mid-order.diagnose', description: 'Diagnose mid-order flow', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'presale-order-id', type: 'str', required: true }], columns: orderColumns }),
  entry({ name: 'supply-presale.validate', description: 'Validate supply-presale flow', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str' }, { name: 'company-id', type: 'str' }], columns: orderColumns }),
  entry({ name: 'supply-presale.submit', description: 'Submit supply-presale flow only when an API runtime is wired', audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'activity-id', type: 'str' }, { name: 'company-id', type: 'str' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['submitted', 'status', 'message'] }),
  entry({ name: 'supply-presale.diagnose', description: 'Diagnose supply-presale flow', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }], columns: orderColumns }),
  entry({ name: 'pickup.validate', description: 'Validate pickup flow', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }, { name: 'file', type: 'path' }], columns: orderColumns }),
  entry({ name: 'pickup.submit', description: 'Submit pickup flow only when an API runtime is wired', audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }, { name: 'file', type: 'path' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['submitted', 'status', 'message'] }),
  entry({ name: 'pickup.diagnose', description: 'Diagnose pickup flow', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }], columns: orderColumns }),
  entry({ name: 'new-store-order.validate', description: 'Validate new-store-order flow', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path' }], columns: orderColumns }),
  entry({ name: 'new-store-order.submit', description: 'Submit new-store-order flow only when an API runtime is wired', audience: 'customer', access: 'financial', strategy: readToken, args: [{ name: 'file', type: 'path' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['submitted', 'status', 'message'] }),
  entry({ name: 'new-store-order.diagnose', description: 'Diagnose new-store-order flow', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'new-store-order-id', type: 'str', required: true }], columns: orderColumns }),
  entry({ name: 'mid-order.activity', description: 'Read middle/short-term presale activity detail', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str', required: true }], columns: ['activityId', 'activityName', 'status'] }),
  entry({ name: 'mid-order.companies', description: 'List companies available for a middle/short-term activity', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str', required: true }], columns: ['companyId', 'companyName', 'whiteRole'] }),
  entry({ name: 'mid-order.models', description: 'List order models for a middle/short-term activity and company', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str', required: true }, { name: 'company-id', type: 'str' }], columns: ['orderModelId', 'orderModelName'] }),
  entry({ name: 'mid-order.rules', description: 'List order rules for a middle/short-term order model', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str', required: true }, { name: 'order-model-id', type: 'str', required: true }], columns: ['orderRuleId', 'ruleName', 'threshold'] }),
  entry({ name: 'mid-order.items', description: 'List products in a middle/short-term activity or model rule scope', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str', required: true }, { name: 'order-model-id', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['itemCode', 'skcCode', 'skuCode'] }),
  entry({ name: 'mid-order.rule-status', description: 'Calculate middle/short-term order rule standard status from a draft', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: ['phase', 'status', 'items'] }),
  entry({ name: 'mid-order.pickup-list', description: 'List pickup orders related to a middle/short-term presale order', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'presale-order-id', type: 'str', required: true }], columns: ['pickupOrderId', 'status'] }),
  entry({ name: 'supply-presale.activity', description: 'Read supply presale activity detail', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str' }], columns: ['activityId', 'activityName', 'status'] }),
  entry({ name: 'supply-presale.items', description: 'List supply presale products', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str' }], columns: ['itemCode', 'skuCode', 'status'] }),
  entry({ name: 'supply-presale.cart', description: 'Read supply presale waiting order/cart', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'activity-id', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['skuCode', 'quantity', 'status'] }),
  entry({ name: 'supply-presale.add', description: 'Add a SKU to a supply presale waiting order with write gate', audience: 'customer', access: 'write', strategy: readToken, args: [{ name: 'activity-id', type: 'str', required: true }, { name: 'sku-code', type: 'str', required: true }, { name: 'qty', type: 'number', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'supply-presale.cancel', description: 'Cancel a supply presale order with destructive gate', audience: 'customer', access: 'destructive', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'report.supply-pickup-activity', description: 'Probe supply presale pickup status by activity batch dimension', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'activity-query', type: 'str' }, { name: 'activity-ids', type: 'csv' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }, { name: 'only-unfulfilled', type: 'bool' }, { name: 'pickup-activity-status', type: 'str' }], columns: ['activities', 'activityIdList', 'pickupActivityRows', 'pickupActivityTotals'] }),
  entry({ name: 'report.supply-pickup-customer', description: 'Probe supply presale pickup rate by customer and distributor dimension', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'activity-query', type: 'str' }, { name: 'activity-ids', type: 'csv' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }, { name: 'company-code', type: 'csv' }, { name: 'company-name', type: 'str' }, { name: 'distributor-code', type: 'csv' }, { name: 'distributor-name', type: 'str' }], columns: ['activities', 'activityIdList', 'customerRows', 'customerGroupRows', 'customerTotals'] }),
  entry({ name: 'report.pickup-customer-skc', description: 'Aggregate pickup rate and pickup/source-order details by customer and SKC', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'activity-query', type: 'str' }, { name: 'source', type: 'enum:supply|mid|all' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }, { name: 'company-code', type: 'str' }, { name: 'company-name', type: 'str' }, { name: 'distributor-code', type: 'str' }, { name: 'distributor-name', type: 'str' }, { name: 'format', type: 'enum:json|csv' }, { name: 'csv', type: 'bool' }], columns: ['pickupScopeRows', 'sourceOrderScopeRows', 'meta'] }),
  entry({ name: 'report.presale-business', description: 'Generate a summary and Excel detail workbook for flexible-supply or middle/short-term presale business', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'source', type: 'enum:supply|mid' }, { name: 'start-date', type: 'str', required: true }, { name: 'end-date', type: 'str', required: true }, { name: 'output', type: 'path', required: true }, { name: 'activity-query', type: 'str' }, { name: 'page-size', type: 'number' }, { name: 'export-timeout-ms', type: 'number' }, { name: 'export-poll-interval-ms', type: 'number' }], columns: ['activities', 'orderRows', 'orderTotals', 'pickupActivityRows', 'pickupActivityTotals', 'customerRows', 'customerTotals', 'summary', 'amountBasis', 'output'] }),
  entry({ name: 'pickup.list', description: 'List pickup orders', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'status', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['pickupOrderId', 'status'] }),
  entry({ name: 'pickup.get', description: 'Read pickup order detail', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }], columns: ['pickupOrderId', 'status'] }),
  entry({ name: 'pickup.items', description: 'Read pickup order items', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }, { name: 'go-pickup', type: 'bool' }], columns: ['skuCode', 'availableQty', 'pickupQty'] }),
  entry({ name: 'pickup.related-presale', description: 'List presale orders related to a pickup order', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }], columns: ['presaleOrderId', 'status'] }),
  entry({ name: 'pickup.refuse', description: 'Refuse a pickup order with destructive gate', audience: 'customer', access: 'destructive', strategy: readToken, args: [{ name: 'pickup-order-id', type: 'str', required: true }, { name: 'reason', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'new-store-order.list', description: 'List new-store orders', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'status', type: 'str' }, { name: 'company-id', type: 'str' }], columns: ['newStoreOrderId', 'status'] }),
  entry({ name: 'new-store-order.get', description: 'Read new-store order detail', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'new-store-order-id', type: 'str', required: true }], columns: ['newStoreOrderId', 'status'] }),
  entry({ name: 'new-store-order.items', description: 'Read new-store order items', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'new-store-order-id', type: 'str', required: true }], columns: ['itemCode', 'skuCode', 'availableQty'] }),
  entry({ name: 'new-store-order.confirm-plan', description: 'Run new-store pickup check and orderConfirm sequence', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'new-store-order-id', type: 'str', required: true }, { name: 'batch-no', type: 'str' }], columns: ['steps'] }),
  entry({ name: 'new-store-order.relation-orders', description: 'List B2B orders generated from a new-store order', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'new-store-order-id', type: 'str', required: true }], columns: ['orderNo', 'status'] }),
  entry({ name: 'pending-order.source-type', description: 'Check whether a pending order should use pending or normal order detail flow', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }], columns: ['orderSourceType'] }),
  entry({ name: 'pending-order.detail', description: 'Read pending-review order detail from mini or middle-ground endpoint', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }, { name: 'middle-ground', type: 'bool' }], columns: ['orderNo', 'companyId', 'addressInfo'] }),
  entry({ name: 'pending-order.review-check', description: 'Precheck pending-review approval payload', audience: 'customer', access: 'read', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }], columns: ['passOrderIds', 'failExportReqs'] }),
  entry({ name: 'pending-order.review', description: 'Approve a pending-review order from a JSON payload with write gate', audience: 'customer', access: 'write', strategy: readToken, args: [{ name: 'file', type: 'path', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }, { name: 'mini', type: 'bool' }], columns: ['orderNo', 'status'] }),
  entry({ name: 'pending-order.cancel', description: 'Cancel a pending-review order through the mini endpoint with destructive gate', audience: 'customer', access: 'destructive', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['ok'] }),

  entry({ name: 'ops.address.list', description: 'List store receiving addresses through hr/mb2bcrd3/list', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }], columns: ['fid', 'provinceName', 'cityName', 'regionName'] }),
  entry({ name: 'ops.address.get', description: 'Read one receiving address through hr/mb2bcrd3/getById', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'address-id', type: 'str', required: true }], columns: ['fid', 'provinceName', 'cityName', 'regionName'] }),
  entry({ name: 'ops.address.check', description: 'Check store receiving address completeness for order approval failures', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }], columns: ['complete', 'blockingIssues', 'nextActions'] }),
  entry({ name: 'ops.address.patch', description: 'Patch a manual receiving address by preserving the full address list and calling hr/mb2bcrd3/saveOrUpdate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }, { name: 'address-id', type: 'str', required: true }, { name: 'province-name', type: 'str' }, { name: 'city-name', type: 'str' }, { name: 'region-name', type: 'str' }, { name: 'con-address', type: 'str' }, { name: 'province-code', type: 'str' }, { name: 'city-code', type: 'str' }, { name: 'region-code', type: 'str' }, { name: 'consignee', type: 'str' }, { name: 'consi-phone', type: 'str' }, { name: 'file', type: 'path' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.address.create', description: 'Create a manual store receiving address through hr/mb2bcrd3/saveOrUpdate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }, { name: 'province-name', type: 'str', required: true }, { name: 'city-name', type: 'str', required: true }, { name: 'region-name', type: 'str', required: true }, { name: 'con-address', type: 'str', required: true }, { name: 'consignee', type: 'str', required: true }, { name: 'consi-phone', type: 'str', required: true }, { name: 'province-code', type: 'str' }, { name: 'city-code', type: 'str' }, { name: 'region-code', type: 'str' }, { name: 'default', type: 'bool' }, { name: 'file', type: 'path' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.address.update', description: 'Edit a manual store receiving address through hr/mb2bcrd3/saveOrUpdate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }, { name: 'address-id', type: 'str', required: true }, { name: 'province-name', type: 'str' }, { name: 'city-name', type: 'str' }, { name: 'region-name', type: 'str' }, { name: 'con-address', type: 'str' }, { name: 'province-code', type: 'str' }, { name: 'city-code', type: 'str' }, { name: 'region-code', type: 'str' }, { name: 'consignee', type: 'str' }, { name: 'consi-phone', type: 'str' }, { name: 'default', type: 'bool' }, { name: 'file', type: 'path' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.address.set-default', description: 'Set the default store receiving address while preserving other addresses', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }, { name: 'address-id', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.address.delete', description: 'Delete a manual store receiving address by saving the remaining address list', audience: 'ops', access: 'destructive', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }, { name: 'address-id', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),

  entry({ name: 'ops.order.diagnose', description: 'Diagnose an order using existing order detail APIs and local rule extraction', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str' }, { name: 'order-id', type: 'str' }, { name: 'type', type: 'str' }], columns: orderColumns }),
  entry({ name: 'ops.order.diagnose-pending', description: 'Diagnose a pending-review order and surface address completeness failures', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }], columns: orderColumns }),
  entry({ name: 'ops.order.timeline', description: 'Read pending-review detail as a timeline anchor; full timeline facade is not present', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-id', type: 'str', required: true }], columns: ['timeline'] }),
  entry({ name: 'ops.order.relations', description: 'Read normal order detail by order number for relation diagnosis', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str', required: true }], columns: ['relation'] }),
  entry({ name: 'ops.order.blocking-reasons', description: 'Inspect local draft blocking reasons without submitting', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str' }, { name: 'file', type: 'path' }], columns: ['blockingIssues'] }),
  entry({ name: 'ops.order.split-check', description: 'Run local split readiness checks for pickup/grouped orders without executing split', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str' }, { name: 'pickup-order-id', type: 'str' }], columns: ['ok', 'blockingIssues'] }),
  entry({ name: 'ops.order.sync-check', description: 'Run local sync status interpretation before requesting manual SAP or async sync handling', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str' }, { name: 'presale-order-id', type: 'str' }], columns: ['ok', 'warnings'] }),
  entry({ name: 'ops.order.export', description: 'Start order export through file/order/exportOrder and normalize async export response', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str', required: true }], columns: ['mode', 'taskId', 'downloadUrl'] }),

  entry({ name: 'ops.product.master.search', description: 'Search product master data through product/itemSearch/search', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }, { name: 'keyword', type: 'str' }], columns: ['itemCode', 'itemName'] }),
  entry({ name: 'ops.product.master.get', description: 'Read product master detail through product/item/spec/getSpuDetailByItemId', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str', required: true }], columns: ['itemCode', 'skcCode', 'skuCode'] }),
  entry({ name: 'ops.product.master.import', description: 'Import product master data through file/import/product/mitem/excelAdd with write gate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'input', type: 'path', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.product.apply.list', description: 'List product application records through product/mitemcomp/list', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }], columns: ['itemCode', 'companyId'] }),
  entry({ name: 'ops.product.apply.update', description: 'Update product application through product/mitemcomp/opt with write gate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'input', type: 'path', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.product.apply.add', description: 'Add one product to a store product application through product/mitemcomp/opt with write gate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'item-code', type: 'str', required: true }, { name: 'company-id', type: 'str' }, { name: 'default-store', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'affected', 'item', 'company', 'apiCalls'] }),
  entry({ name: 'ops.product.group.list', description: 'List product groups through product/item/group/list', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }], columns: ['groupId', 'itemCode'] }),
  entry({ name: 'ops.product.package.list', description: 'List product package company applications through product/pag/comp/list', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }], columns: ['packageId', 'companyId'] }),
  entry({ name: 'ops.product.tag.list', description: 'List product activity labels through product/activitylabel/getActivityLabelOfConditions', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }], columns: ['labelCode', 'labelName'] }),
  entry({ name: 'ops.product.price.check', description: 'Check B2B price list types through product/pricelist/b2b/types', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str', required: true }], columns: ['priceType', 'price'] }),
  entry({ name: 'ops.product.launch-check', description: 'Diagnose product launch readiness across master data, image, package item config, and store package application', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str', required: true }, { name: 'company-id', type: 'str' }, { name: 'company-code', type: 'str' }, { name: 'company-name', type: 'str' }], columns: ['overallStatus', 'checks', 'blockingIssues', 'warnings', 'nextActions'] }),
  entry({ name: 'ops.product.launch-setup', description: 'Run the full batch product launch setup chain: MDM sync, image sync, package item config, and store package application', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'item-codes', type: 'csv', required: true }, { name: 'package-names', type: 'csv', required: true }, { name: 'company-codes', type: 'csv', required: true }, { name: 'merchant-ids', type: 'csv' }, { name: 'sync-stock-logistics-pic', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'affected', 'itemCodes', 'packageNames', 'companyCodes', 'imageSyncTarget', 'apiCalls'] }),
  entry({ name: 'ops.product.image-sync', description: 'Trigger product image sync through product/itemPicAsyncByItemCode with write gate', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'item-code', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),

  entry({ name: 'ops.stock.query', description: 'Query product stock statistics through product/itemStock/statistics/page', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }, { name: 'sku-code', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['itemCode', 'skuCode', 'stockQty'] }),
  entry({ name: 'ops.stock.sync-status', description: 'Query stock sell-out sync scope through product/item/page/syncStockSellOut', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'item-code', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['itemCode', 'sellOut'] }),
  entry({ name: 'ops.customer.get', description: 'Read company/customer info by companyId or companyCode through hr/sysCompany query APIs', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'company-id', type: 'str' }, { name: 'company-code', type: 'str' }], columns: ['companyId', 'companyCode', 'companyName'] }),
  entry({ name: 'ops.store.get', description: 'Read one store/company by companyId through hr/sysCompany/queryCompanyInfoById', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'company-id', type: 'str', required: true }], columns: ['companyId', 'companyName'] }),
  entry({ name: 'ops.store.mdm.sync-by-codes', description: 'Pull store master data from MDM into the store staging table by store codes', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'company-codes', type: 'csv', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.store.mdm.sync-by-time', description: 'Pull store master data from MDM into the store staging table by update time range', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'from', type: 'str', required: true }, { name: 'to', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.store.mdm.page', description: 'List store MDM staging records through hr/mdmStore/page', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'store-code', type: 'str' }, { name: 'store-name', type: 'str' }, { name: 'sync-status', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['storeCode', 'storeName', 'syncStatus'] }),
  entry({ name: 'ops.store.mdm.diff', description: 'Compare one store code between current store profile and MDM staging data', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'company-code', type: 'str', required: true }], columns: ['currentCompanyInfo', 'mdmCompanyInfo'] }),
  entry({ name: 'ops.store.mdm.confirm', description: 'Confirm selected or all store MDM staging records into store profiles', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'company-codes', type: 'csv' }, { name: 'sync-all', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.retailer.get', description: 'Query retailer/distributor role page through hr/sysCompany/queryDistributorRole/middleGround', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'distributor-id', type: 'str' }, { name: 'sword', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['distributorId', 'companyName'] }),
  entry({ name: 'ops.retailer.mdm.sync-by-codes', description: 'Pull retailer master data from MDM into the retailer staging table by retailer codes', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'distributor-codes', type: 'csv', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.retailer.mdm.sync-by-time', description: 'Pull retailer master data from MDM into the retailer staging table by update time range', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'from', type: 'str', required: true }, { name: 'to', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.retailer.mdm.page', description: 'List retailer MDM staging records through hr/mdmRetailer/page', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'retailer-code', type: 'str' }, { name: 'retailer-name', type: 'str' }, { name: 'sync-status', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['retailerCode', 'retailerName', 'syncStatus'] }),
  entry({ name: 'ops.retailer.mdm.diff', description: 'Compare one retailer code between current retailer profile and MDM staging data', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'distributor-code', type: 'str', required: true }], columns: ['currentDistributorInfo', 'mdmDistributorInfo'] }),
  entry({ name: 'ops.retailer.mdm.confirm', description: 'Confirm selected or all retailer MDM staging records into retailer profiles', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'distributor-codes', type: 'csv' }, { name: 'sync-all', type: 'bool' }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'apiCalls'] }),
  entry({ name: 'ops.iam.user', description: 'Query IAM users through hr/iamUser/userPage or detailById', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'user', type: 'str' }, { name: 'id', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['id', 'mobile', 'userName'] }),
  entry({ name: 'ops.iam.role', description: 'Query IAM roles through hr/iamRole/rolePage or detailById', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'role-code', type: 'str' }, { name: 'id', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['id', 'roleCode', 'roleName'] }),
  entry({ name: 'ops.config.get', description: 'Explicitly unsupported until a safe backend configuration facade is provided', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'key', type: 'str', required: true }], columns: ['error'] }),
  entry({ name: 'ops.config.set', description: 'Dry-run only placeholder; actual config writes require a safe backend facade', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'key', type: 'str', required: true }, { name: 'value', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['blocked', 'message'] }),
  entry({ name: 'ops.log.api', description: 'Explicitly unsupported until an API log query facade is mapped for CLI', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'request-id', type: 'str' }, { name: 'order-no', type: 'str' }], columns: ['error'] }),
  entry({ name: 'ops.log.sync-warning', description: 'Explicitly unsupported until a sync warning log facade is mapped for CLI', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'order-no', type: 'str' }, { name: 'item-code', type: 'str' }], columns: ['error'] }),

  entry({ name: 'ops.export.task.list', description: 'List async export tasks through file/asyn/export/b2b/page', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'type', type: 'str' }, { name: 'page-index', type: 'number' }, { name: 'page-size', type: 'number' }], columns: ['taskId', 'status', 'taskUrl'] }),
  entry({ name: 'ops.export.task.get', description: 'Get one async export task by polling file/asyn/export/b2b/page', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'task-id', type: 'str', required: true }], columns: ['taskId', 'status', 'downloadUrl'] }),
  entry({ name: 'ops.export.task.wait', description: 'Poll one async export task until success, failure, or timeout', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'task-id', type: 'str', required: true }, { name: 'timeout', type: 'duration' }], columns: ['taskId', 'status', 'downloadUrl'] }),
  entry({ name: 'ops.export.task.download', description: 'Resolve export download URL through file/export/task/downloadTaskFile and write the file locally', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'task-id', type: 'str', required: true }, { name: 'output', type: 'path', required: true }], columns: ['output', 'bytes'] }),

  entry({ name: 'ops.job.list', description: 'List allowlisted operations jobs', audience: 'ops', access: 'read', strategy: readToken, args: [{ name: 'module', type: 'str' }], columns: ['jobId', 'module', 'status'] }),
  entry({ name: 'ops.job.run', description: 'Dry-run allowlisted jobs; actual run requires a backend facade and explicit confirmation', audience: 'ops', access: 'write', strategy: readToken, args: [{ name: 'job-id', type: 'str', required: true }, { name: 'dry-run', type: 'bool' }, { name: 'confirm', type: 'bool' }, { name: 'reason', type: 'str' }], columns: ['mode', 'jobId'] }),
];

export function listManifest(): CommandManifestEntry[] {
  return COMMAND_MANIFEST;
}

export function getManifest(name: string): CommandManifestEntry | undefined {
  return COMMAND_MANIFEST.find((item) => item.name === name);
}
